import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./test.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className + " bg-[#0b0f11] page "}>
        {children}
      </body>
    </html>
  );
}
