import type { Metadata, ResolvingMetadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { i18n, type Locale } from "../../i18n-config";

const inter = Inter({ subsets: ["latin"] });
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang} dir={params.lang === "he" ? "rtl" : "ltr"}>
      <body className={inter.className + " bg-[#0b0f11] page "}>
        {children}
      </body>
    </html>
  );
}

export async function generateMetadata({
  params,
}: {
  params: { lang: Locale };
  perent: ResolvingMetadata;
}): Promise<Metadata> {
  return {
    title: params.lang === "he" ? "בית" : "Home",
    icons: {
      icon: "/icons8-code-folder-16.png",
    },
  };
}
